### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-3-evaluacion-intermedia-evaferrerasbr#1]
Buen trabajo @evaferrerasbr !

- No puedo sacar ninguna mejora, es la primera vez que me pasa en todas mis promos. Un trabajo excelente!!!
- Muy bien esto de avisar al entrevistador por qué haces o no haces algo, enhorabuena https://github.com/Adalab/modulo-3-evaluacion-intermedia-evaferrerasbr/blob/master/src/components/App.js#L8

![https://media.giphy.com/media/Hc8PMCBjo9BXa/source.gif](https://media.giphy.com/media/Hc8PMCBjo9BXa/source.gif)

### Cuando tengas esto si quieres puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón!!!

**Comment by evaferrerasbr** [comment]
@migueldelmazo Hecho :D
